import os, sys
from setuptools import setup

# Figure out the version number and write it to
#     the main directory
# so that we don't have to import qinfer before it's
# installed. This technique seems to be popular amongst
# scientific libraries for ensuring that PEP-440 is adhered
# to, and that version numbers in __init__.py match those in
# setup.py.

MAJOR = 0
MINOR = 1
PRE = 'b0'
VERSION = "{major}.{minor}{pre}".format(
    major=MAJOR, minor=MINOR, pre=PRE if PRE is not None else ''
)
VERSION_TARGET = 'version.py'

def write_version(filename=VERSION_TARGET):
    contents = """\
# This file is automatically generated by setup.py.
# Do not modify.
version = "{version}"
""".format(version=VERSION)
    
    with open(filename, 'w') as version_file:
        version_file.write(contents)

if os.path.exists(VERSION_TARGET):
    os.remove(VERSION_TARGET)

write_version()

from distutils.core import setup

setup(
    name='topspin_to_python',
    version=VERSION,
    url='https://github.com/whitewhim2718/topspin_to_python',
    download_url='https://github.com/whitewhim2718/topspin_to_python',
    description="Read Bruker TopSpin experiments into Python",
    author='Thomas Alexander',
    author_email='thomasalexander2718@gmail.com',
    packages=[
        'topspin_to_python'
    ],
    install_requires=[
        'numpy',
        'scipy',
        'future>=0.15'
    ],
    test_suite='tests',
    tests_requires=['pytest',
                    'pytest-cov',
                    'pytest-xdist',
                    'coveralls',
                    'pylint'],
    keywords=['topspin','bruker','spectra','fid','ft','nmr'],
    long_description=""" A library to read in and analyze TopSpin experiments.
                        Can perform Fourier transforms (FT), automatically phase FTs,
                        and a variety of other useful data analysis. 

                        This version currently requires Python 2.7 due to library dependencies. 

                        """
)